version: "3.3"
services:
  db:
    image: postgres:14.2
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: qstydydb
    ports:
      - "5432:5432"

volumes:
  db-data:
    driver: local
